### ISSUE TITLE
tsc fails in example project folder

### ISSUE THREAD

**Issue by UnsolvedCypher** [Enderchief/vite-gleam#8]
In the example project folder, running `tsc` produces an error:

```
➜  example git:(master)  pnpm tsc
src/main.ts:4:31 - error TS2307: Cannot find module './counter.gleam' or its corresponding type declarations.

4 import { setup_counter } from "./counter.gleam";
                                ~~~~~~~~~~~~~~~~~


Found 1 error in src/main.ts:4
```

I would expect TypeScript not to produce this error, given that `ts-gleam` tells it how to open `.gleam` files. Interestingly, I don't see this error in my LSP when opening a file. Please let me know if there is any more information I can provide! And thank you for this incredibly useful package 😄

**Comment by UnsolvedCypher** [comment]
It turns out it is expected behavior for `tsc` not to run with the plugin, see https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin .

**Comment by Enderchief** [comment]
`tsc` will not work no matter what since the plugin is just for the LSP to resolve files properly and does not tell the TypeScript compiler anything. The purpose of the plugin is to work with Vite and the `vite-gleam` plugin which does build `*.gleam` properly.
