### ISSUE TITLE
[vite-gleam] Incorrect path resolution for `*.gleam` file

### ISSUE THREAD

**Issue by SLimeyMC** [Enderchief/vite-gleam#9]
I have a vite + gleam + typescripts project where I'm encountering issue when running `npm run dev`. This was caused by `vite-gleam`  trying to open a file at `build\dev\javascript\src\app.mjs`. However, the expected behaviour is for it to open `build\dev\javascript\{project_name}\app.mjs`

This mismatch caused an error with Vite:
```
[vite] Internal server error: ENOENT: no such file or directory, open '.\build\dev\javascript\src\app.mjs'
  Plugin: gleam
  ```
  
  After looking at the code the issue seems to be because of the forward/backward slashes ambiguity with Windows and Linux/macOS

**Comment by Enderchief** [comment]
Thank you.
Should be fixed in vite-gleam `0.4.3`
